### ISSUE TITLE
question: What's the use of the bitwise operator?

### ISSUE THREAD

**Issue by Zhang-theSenile** [fabiensanglard/DoomFirePSX#6]
Hello there, thank you for sharing such an impressive work.
I'm curious about the bitwise operator `&`  used in the `spreadFire()` part.

```javascript
var randIdx = Math.round(Math.random() * 3.0) & 3;
var dst = src - randIdx + 1;
firePixels[dst - FIRE_WIDTH ] = pixel - (randIdx & 1);
```

I cannot figure out the purpose of using these two `&` operator. Could anyone give me some advice please?

**Comment by lebchen** [comment]
First example:

Math.round(Math.random() * 3.0) gives you a number from 0 through 2. If we represent those numbers in binary, and apply the operator with 0011 (3) as second argument, we get:

0000 & 0011 = 0000
0001 & 0011 = 0001
0010 & 0011 = 0010

So this does actually nothing! I am guessing that & 3 was used in the original code as a simplified modulo-operator? In javascript it could also be used instead of Math.round. Here it seems like it serves no purpose, though.



In the second example, I don't really know the context of randIdx, but a bitwise & with 1 would of course reduce randIdx to be either 0 or 1. So it looks to me like he wants a simple "random either 1 or 0" and repurposes the random value. But at the same time, wether you get 0 or 1 is closely related to if randIdx is 0, 1 or 2 in the first place.

**Comment by fabiensanglard** [comment]
Indeed, the AND is useless. Removing it.
