### ISSUE TITLE
New Project Idea: 8-bit Fireplace?

### ISSUE THREAD

**Issue by lexterror** [fabiensanglard/DoomFirePSX#8]
I think it would be a cool project. The only thing really missing is the fireplace and logs. I dont think it would be that difficult to add those to the code. And add a few special FX. Please let me know. Also I was not able to remove the blur from the easyjs script yet, so i used an overlay css blur. This is my mod so far, but would like to end up with something like in the 2nd photo. I think a lot of people would really enjoy it! Thank you!

[PixelFire_1.0.txt](https://github.com/fabiensanglard/DoomFirePSX/files/13326274/PixelFire_1.0.txt)

![Screenshot_20231111-135501](https://github.com/fabiensanglard/DoomFirePSX/assets/16135535/018c2242-715b-4a18-89e2-8d991d61ac07)

![8-Bit-Fireplace-NoLogo-1920x1080-20161125DP-e1542229611148](https://github.com/fabiensanglard/DoomFirePSX/assets/16135535/46918a66-c1cb-47b8-bd6e-9d4aba7e86d9)

**Comment by fabiensanglard** [comment]
Adding a fireplace log is not in line with  Doom video-games. So chance of adding it to this repo is zero.

But feel free to fork the project and add it to your repo :) !

**Comment by lexterror** [comment]
Hi Fabien,

I just completed the js pixel fireplace with my own code from scratch. Check it out:

http://alext.rf.gd/

![Screenshot_20231205-074010](https://github.com/lexterror/Js-Pixel-Fireplace/assets/16135535/8aa842a5-d49e-4342-aeb2-b64259653200)

**Comment by lexterror** [comment]
Hi Fabien,

I'm sharing my latest venture, it's a pixel fireplace using "doom fire" algorithm. It's basically complete at this point. Might try exploring a few enhancements/mods in the future: And there is a log! I hope you don't mind ;)

Also, would not mind feedback. I noticed a lot of creators use "doom fire" algorithm as a starting point for all kinds of "fire" simulations...

Live Demo: 

https://js-pixel-fireplace.sourceforge.io/fireplace.html

**Comment by lexterror** [comment]
Hi Fabien,

This is my latest mod/enhancement of my App. Thank you for promoting your doom fire algorithm!!! :) It really helps a lot of folks.

![preview](https://github.com/fabiensanglard/DoomFirePSX/assets/16135535/532ae5e3-b82e-439d-8e2e-c3cbab802576)

**Comment by lexaterra** [comment]
Hi Fabien,

I customized your doom fire algorithm for my fireplace simulation. Also, I recently got a new phone number from TMobile and got locked out of yahoo/gmail because of 2 factor Auth. It also left me without access to my old github account. It doesnt matter to me really, but I made significant progress with my app and posted it on itch.io. 

Sorry if I seem a bit out of sorts, but I like engaging people in what I consider meaningful conversation. I know the motto "you have to make it own your own", but its really the wrong way of looking at it. In any case...

Sidenote: It was never my objective to become a pro at anything... life is too short. I know my "material" is amateurish and is poorly written/commented, but it has meaning!

https://lexaterra.itch.io/pixel-fireplace-mobile

https://js-pixel-fireplace.sourceforge.io/fireplace.html

lexterror,

Thank you!
